### ISSUE TITLE
UUIDs to be replaced by complete URIs in APIs

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-framework#92]
@apdavison has proposed [here](https://github.com/apdavison/hbp-validation-client/pull/4) that we have the APIs (wherever applicable) return the URI instead of UUID, and also accept the URI as input instead of UUID for retrieving models/tests/results.

**Comment by apdavison** [comment]
Note that the URI for a model should be 
`https://validation-v1.brainsimulation.eu/scientific-model/<uuid>`
(or https://validation-v1.brainsimulation.eu/models/<uuid> if we adopt #88)
rather than
`https://validation-v1.brainsimulation.eu/scientific-model/?id=<uuid>`, which I think is the current API.

This means that there isn't even any question of having the URI "as input for retrieving a model", the URI points directly to the model.

**Comment by apdavison** [comment]
By the way, this will require quite a lot of code changes, I think, but at the same time it will be invisible to end users (who will use the Python client and the Collaboratory apps), so this is low priority, we should focus first on finishing the apps and the Python client.

**Comment by apdavison** [comment]
In v2 of the REST API we return both the uri and the uuid. I've changed my mind on accepting the uri as input, it makes for very messy urls and anyway we may move the server address so then the uris are not persistent.
